import streamlit as st
import time


# Import the functions/logic from your other files
# from llm_engine import get_hypocrisy_score
# from graph_viz import create_risk_graph

# --- MOCK FUNCTIONS FOR THE EXAMPLE ---
# In your real app, you'd call your actual functions
def get_hypocrisy_score(claim, evidence):
	st.session_state.score = 8.5  # Hardcode for the demo
	return {
		"contradiction": "Yes",
		"severity": 8.5,
		"explanation": "The company was fined $50M for the exact thing it claimed to prevent."
	}


def create_risk_graph_html(score):
	# In your real app, this would call your NetworkX/PyVis code
	# and save to a file. Here, we just return the file path.
	# (Assume 'risk_graph.html' was generated by your other script)
	return "risk_graph.html"


# --- END MOCK FUNCTIONS ---


st.set_page_config(layout="wide")
st.title("ESG 'Corporate Lie Detector' 🕵️")

# Initialize session state for the score
if 'score' not in st.session_state:
	st.session_state.score = 0.0

col1, col2 = st.columns(2)

with col1:
	st.header("1. Contradiction Analysis (LLM)")
	company = st.selectbox("Select Target Company", ["TechCo", "OilCo (mock)", "RetailCo (mock)"])

	# Hardcode the data for your one demo company
	if company == "TechCo":
		claim = "We are committed to 100% user data privacy and security."
		evidence = "TechCo fined $50M for major data breach violating user privacy."

		st.text_area("Official ESG Claim:", value=claim, height=100, disabled=True)
		st.text_area("Contradictory Evidence (News/Legal):", value=evidence, height=100, disabled=True)

		if st.button("Analyze Risk"):
			with st.spinner("Calling LLM to analyze..."):
				time.sleep(2)  # Simulate API call
				result = get_hypocrisy_score(claim, evidence)

				st.subheader("Analysis Result:")
				st.json(result)

				st.metric(label="Hypocrisy Score", value=f"{result['severity']}/10", delta="High Risk")

with col2:
	st.header("2. Risk Contagion Map (GNN)")

	if st.session_state.score > 0:
		st.info("GNN simulation is running based on the new hypocrisy score.")

		# Generate the graph HTML
		html_file_path = create_risk_graph_html(st.session_state.score)

		# Display the interactive HTML file
		try:
			with open(html_file_path, 'r', encoding='utf-8') as f:
				html_code = f.read()
				st.components.v1.html(html_code, height=750)
		except FileNotFoundError:
			st.error("Graph HTML file not found. Please generate it first.")

	else:
		st.info("Click 'Analyze Risk' to generate the contagion map.")